# Generated by Django 2.2.10 on 2020-02-26 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=12)),
                ('customer_surname', models.CharField(max_length=20)),
                ('customer_phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Farmacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=50, null=True)),
                ('house', models.TextField(null=True)),
                ('street', models.CharField(max_length=50, null=True)),
                ('state_province', models.CharField(max_length=50, null=True)),
                ('manager', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(db_index=True, max_length=250)),
                ('product_manufacturer', models.CharField(blank=True, max_length=250, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('product_photo', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.FloatField(blank=True, null=True)),
                ('farmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Farmacy')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available', to='app.Product')),
            ],
            options={
                'db_table': 'product_availability',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_price', models.FloatField()),
                ('order_quantity_product', models.FloatField()),
                ('order_pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Farmacy')),
                ('order_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registry_total_price', models.FloatField()),
                ('registry_date', models.DateField(blank=True, null=True)),
                ('registry_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Customer')),
            ],
        ),
    ]
