# Generated by Django 2.2.10 on 2020-02-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order_quantity_product',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_cost_product',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='registry_total_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
