# Generated by Django 2.2.10 on 2020-03-27 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='pharmacy',
            options={'verbose_name': 'Аптека', 'verbose_name_plural': 'Аптеки'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Наименование', 'verbose_name_plural': 'Номенклатура'},
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'В обработке'), (3, 'Выполнен')], default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=12, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_surname',
            field=models.CharField(max_length=20, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Pharmacy', verbose_name='Аптека'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Сумма заказа'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='cost_product',
            field=models.FloatField(blank=True, null=True, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.FloatField(blank=True, null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='pharmacy_name',
            field=models.CharField(max_length=255, verbose_name='Аптека'),
        ),
    ]
