# Generated by Django 2.2.10 on 2020-02-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200227_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='registry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
