# Generated by Django 2.2.2 on 2019-07-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_product_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmacy',
            name='farmacy_id',
        ),
        migrations.AddField(
            model_name='farmacy',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmacy',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmacy',
            name='street',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
