# Generated by Django 2.2.2 on 2019-07-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190709_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmacy',
            name='house',
            field=models.TextField(),
        ),
    ]
