# Generated by Django 2.2.10 on 2020-02-27 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200227_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Farmacy'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Product'),
        ),
    ]
