# Generated by Django 2.2.10 on 2020-03-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200328_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='city',
            field=models.CharField(max_length=50, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='house',
            field=models.CharField(max_length=50, null=True, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='manager',
            field=models.CharField(max_length=50, null=True, verbose_name='Заведующая'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='phone',
            field=models.CharField(max_length=50, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='state_province',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='street',
            field=models.CharField(max_length=50, null=True, verbose_name='Улица'),
        ),
    ]
