# Generated by Django 2.2.6 on 2019-10-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190831_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AlterField(
            model_name='farmacy',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='farmacy',
            name='house',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='farmacy',
            name='manager',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='farmacy',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='farmacy',
            name='state_province',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
