# Generated by Django 2.2.6 on 2019-12-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
