# Generated by Django 2.2.6 on 2020-02-09 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_customer_order_orderregistry'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_quantity_product', models.FloatField()),
                ('order_value_product', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_quantity_product',
            new_name='registry_total_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_value_product',
        ),
        migrations.AddField(
            model_name='order',
            name='registry_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='registry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
        migrations.AlterModelTable(
            name='order',
            table=None,
        ),
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
        migrations.DeleteModel(
            name='OrderRegistry',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Product'),
        ),
    ]
